export default function () {
  return [
    {title:'JavaScript: The Good Parts', pages: 101},
    {title: 'Harry Potter', pages: 39},
    {title: 'The Dark Tower', pages: 85},
    {title: 'Elequent Ruby', pages: 1}
  ]
}
// our application state is generated by the books reducer which always returns an array of books
